
matrix:
  include:
    - language: python
      cache: pip
      install:
        - pip install pytest-cov pytest-benchmark
      before_script:
        - cd python
      script:
        - export PYTHONPATH=`pwd`
        - pytest -v --cov=lognplot

    - language: rust
      cache: cargo
      script:
        - cargo test -p lognplot
        - cargo build --release -p clognplot
        - make -C demo/c
